package modelo;
// Generated 30/03/2018 01:55:12 PM by Hibernate Tools 4.3.1



/**
 * PreguntaDe generated by hbm2java
 */
public class PreguntaDe  implements java.io.Serializable {


     private int idPreguntaDe;
     private Pregunta pregunta;
     private Usuario usuario;

    public PreguntaDe() {
    }

	
    public PreguntaDe(int idPreguntaDe) {
        this.idPreguntaDe = idPreguntaDe;
    }
    public PreguntaDe(int idPreguntaDe, Pregunta pregunta, Usuario usuario) {
       this.idPreguntaDe = idPreguntaDe;
       this.pregunta = pregunta;
       this.usuario = usuario;
    }
   
    public int getIdPreguntaDe() {
        return this.idPreguntaDe;
    }
    
    public void setIdPreguntaDe(int idPreguntaDe) {
        this.idPreguntaDe = idPreguntaDe;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


